language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_script:
  # something@example.com
  - git config user.email "${GIT_EMAIL}"
  # First Last
  - git config user.name "${GIT_NAME}"

script:
  - ./gradlew clean publish -i --continue
  - ./gradlew -b finalize.gradle -PgithubRepo=${GIT_URL} publishGhPages -i